---

- hosts: localhost
  connection: local
  become: yes
  tasks:


   - name: Install Packages
     package:
       name: "{{ item }}"
       state: present
     with_items:
      - iputils-ping
      - dnsutils
      - unzip
      - build-essential
      - golang-go
      - libnss3


   - name: Install VSCode
     get_url:
       url: https://go.microsoft.com/fwlink/?LinkID=620884
       dest: /opt/vscode.tar.gz
       mode: 0440
   - name: Unpack VSCode
     unarchive:
       src: /opt/vscode.tar.gz
       dest: /opt
   - name: Symlink VSCode
     file:
       src: /opt/VSCode-linux-x64/bin/code
       dest: /usr/local/bin/code
       state: link
