---

- hosts: localhost
  connection: local
  become: yes
  tasks:
  
  
   - name: Get logname
     command: logname
     register: logname
   - name: Set facts
     set_fact:
       logname: "{{ logname.stdout }}"
       home_directory: "/home/{{ logname.stdout }}"


   - name: Install Packages
     package:
       name: "{{ item }}"
       state: present
     with_items:
      - iputils-ping
      - dnsutils
      - unzip
      - build-essential
      - golang-go
      - libnss3
      
      
   - name: Checkout Goenv
     become: yes
     become_user: "{{ logname }}"
     git:
       repo: https://github.com/syndbg/goenv.git
       dest: "{{ home_directory }}/.goenv"
       version: 1.23.3
   - name: Add GOENV_ROOT
     become: yes
     become_user: "{{ logname }}"
     lineinfile: 
       path: "{{ home_directory }}/.bashrc"
       line: "export GOENV_ROOT=$HOME/.goenv"
   - name: Add GOENV to Path
     become: yes
     become_user: "{{ logname }}"
     lineinfile: 
       path: "{{ home_directory }}/.bashrc"
       line: "export PATH=$GOENV_ROOT/bin:$PATH"
   - name: Add Goenv Init
     become: yes
     become_user: "{{ logname }}"
     lineinfile: 
       path: "{{ home_directory }}/.bashrc"
       line: "eval \"$(goenv init -)\""


   - name: Install VSCode
     get_url:
       url: https://go.microsoft.com/fwlink/?LinkID=620884
       dest: /opt/vscode.tar.gz
       mode: 0440
   - name: Unpack VSCode
     unarchive:
       src: /opt/vscode.tar.gz
       dest: /opt
   - name: Symlink VSCode
     file:
       src: /opt/VSCode-linux-x64/bin/code
       dest: /usr/local/bin/code
       state: link
   - name: Create user data directory
     file:
       path: "{{ home_directory }}/.vscode"
       owner: "{{ logname }}"
       group: "{{ logname }}"
       state: directory
   - name: Create config directory
     file:
       path: "{{ home_directory }}/.config/Code/User"
       owner: "{{ logname }}"
       group: "{{ logname }}"
       state: directory
   - name: Install extensions
     become: yes
     become_user: "{{ logname }}"
     command: "/usr/local/bin/code --install-extension {{ item }}"
     with_items:
       - marlon407.code-groovy
       - ms-mssql.mssql
       - ms-python.python
       - ms-vscode.Go
       - PeterJausovec.vscode-docker
       - redhat.java
       - secanis.jenkinsfile-support
   - name: Install settings
     become: yes
     become_user: "{{ logname }}"
     template:
       src: vscode/settings.json.tpl
       dest: "{{ home_directory }}/.config/Code/User/settings.json"
