---

- hosts: localhost
  connection: local
  become: yes
  tasks:
  
  
   - name: Get logname
     command: logname
     register: logname
   - debug: var=logname


   - name: Install Packages
     package:
       name: "{{ item }}"
       state: present
     with_items:
      - iputils-ping
      - dnsutils
      - unzip
      - build-essential
      - golang-go
      - libnss3


   - name: Install VSCode
     get_url:
       url: https://go.microsoft.com/fwlink/?LinkID=620884
       dest: /opt/vscode.tar.gz
       mode: 0440
   - name: Unpack VSCode
     unarchive:
       src: /opt/vscode.tar.gz
       dest: /opt
   - name: Symlink VSCode
     file:
       src: /opt/VSCode-linux-x64/bin/code
       dest: /usr/local/bin/code
       state: link
   - name: Create user data directory
     file:
       path: "/home/{{ logname }}/.vscode"
       owner: "{{ logname }}"
       group: "{{ logname }}"
       state: directory
   - name: Create config directory
     file:
       path: "/home/{{ logname }}/.config/Code/User"
       owner: "{{ logname }}"
       group: "{{ logname }}"
       state: directory
   - name: Install extensions
     become: yes
     become_user: "{{ logname }}"
     command: "/usr/local/bin/code --install-extension {{ item }}"
     with_items:
       - marlon407.code-groovy
       - ms-mssql.mssql
       - ms-python.python
       - ms-vscode.Go
       - PeterJausovec.vscode-docker
       - redhat.java
       - secanis.jenkinsfile-support
   - name: Install settings
     become: yes
     become_user: "{{ logname }}"
     template:
       src: vscode/settings.json.tpl
       dest: "/home/{{ logname }}/.config/Code/User/settings.json"
