---

- hosts: localhost
  connection: local
  become: yes
  tasks:

   - name: Install Packages
     package: name="{{ item }}" state=present
     with_items:
      - build-essential
      - golang-go
      - iputils-ping
